---
custom_rdp_properties: "audiocapturemode:i:1;audiomode:i:0;camerastoredirect:s:*;redirectsmartcards:i:1;targetisaadjoined:i:1;usbdevicestoredirect:s:*"
load_balancer_type: "DepthFirst"
maximum_sessions_allowed: 4
